function showSociotypeDescription(element) {
	switch(element.id)
	{
		case "t0":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Don Quixote&nbsp;&mdash; “Seeker”</h3><p class="representatives">Albert Einstein<br />Carlos Castaneda<br />Baron Münchhausen<br />Professor Farnsworth (“Futurama”)<br />Doc (“Back to the Future”)</p><p>Intuitive-logical extraverts (ILE) are born researchers and inventors. They study not only useful things, but “everything that&nbsp;is&nbsp;interesting,” from mechanisms to&nbsp;caterpillars. There’s nothing they like better than to&nbsp;read about something mysterious.</p><p>ILE are aimed at&nbsp;using their knowledge in&nbsp;practice, but are rarely interested in&nbsp;material profit from their discoveries. Thanks to&nbsp;their intuition and logic ILE are capable of&nbsp;quickly studying a&nbsp;great volume of&nbsp;material on&nbsp;a&nbsp;chosen topic to&nbsp;pave the way for the followers. Their theories can often result in&nbsp;a&nbsp;turn-over in&nbsp;the traditional views.</p><p>ILE’s drawback is their constant strive for defending their ideals. Decency is the feature they treasure the most. Their steep demands make&nbsp;it difficult for them to&nbsp;accept life and people’s actions as&nbsp;they&nbsp;are. Sometimes they fight not real enemies, but imaginary windmills. At&nbsp;every insight ILE try to&nbsp;share their thoughts with those around them without thinking whether it&nbsp;is the right time and place. Unfortunately, they are not always ready to&nbsp;listen to&nbsp;others and often interrupt them.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Intuitive_Logical_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t1":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Alexandre Dumas&nbsp;&mdash; “Mediator”</h3><p class="representatives">Porthos (“The Three Musketeers”)<br />Bernadette (“Big Bang Theory”)<br />Winnie-the-Pooh</p><p>Sensoric-ethical introverts (SEI) are masters of&nbsp;compromise. Their mission&nbsp;is to&nbsp;fully enjoy their life without interfering with other people’s ways.</p><p>As&nbsp;a&nbsp;rule, SEI have extremely cozy homes, where they like to&nbsp;relax their soul and body with comfort.</p><p>SEI spend their spare time cooking&nbsp;&mdash; that&nbsp;is their favourite activity. They are born designers and image-makers. They have a&nbsp;strong sense of&nbsp;colour, form and size.</p><p>When gathered with friends at&nbsp;a&nbsp;dinner table, SEI often become masters of&nbsp;ceremonies, jokers, the&nbsp;soul of&nbsp;the party. Their funny stories or&nbsp;anecdotes can warm even the gloomiest person.</p><p>SEI’s drawback&nbsp;is their inability to&nbsp;make strategic decisions. They lack persistence, perseverance and foresight in&nbsp;important matters. SEI live day&nbsp;by&nbsp;day and hate thinking about the future. They tend to&nbsp;waste a&nbsp;lot of&nbsp;time on&nbsp;trifles.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Sensing_Ethical_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t2":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Victor Hugo&nbsp;&mdash; “Enthusiast”</h3><p class="representatives">Sandra Bullock<br />Tigger (“Winnie-the-Pooh”)<br />Phoebe Buffay (“Friends”)</p><p>Ethical-sensoric extraverts (ESE) are incorrigible optimists, who always try to&nbsp;keep the stiff upper lip and see a&nbsp;silver lining in&nbsp;any situation. They love to&nbsp;eat well and have a&nbsp;drink with friends outdoors. They are fascinated by&nbsp;all sorts of ideas and can discuss weather, business, TV&nbsp;shows, and&nbsp;other people’s lives for hours over phone.</p><p>ESE are optimists and hate sadness and idleness. They often find self-fulfillment in&nbsp;advertising, as&nbsp;they can sell the most slow-moving articles to&nbsp;the&nbsp;most fastidious buyer&nbsp;&mdash; not for the sake of&nbsp;profit, but on&nbsp;principle.</p><p>ESE’s drawback&nbsp;is their lack of&nbsp;punctuality. They can be&nbsp;late and fail to&nbsp;deliver&nbsp;&mdash; not because they did not want&nbsp;to, but because it’s hard for them to&nbsp;plan ahead. They also find&nbsp;it difficult to&nbsp;tell the difference between essential and secondary. All’s&nbsp;important to&nbsp;them. This results in&nbsp;incoherence, and important stuff can&nbsp;be left out. Their irrepressible energy is&nbsp;often wasted on&nbsp;trifles, and they can&nbsp;be worn out when it’s&nbsp;time to&nbsp;bring the matter to a&nbsp;close.</p><p>ESE’s weak sense of&nbsp;time shows in&nbsp;their inability to&nbsp;foresee the future.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Ethical_Sensing_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t3":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Robespierre&nbsp;&mdash; “Analyst”</h3><p class="representatives">Immanuel Kant<br />Vladimir Putin<br />Chandler Bing (“Friends”)<br />Sheldon Cooper (“Big Bang Theory”)</p><p>Logical-intuitive introverts (LII) aim at&nbsp;seeing and creating a&nbsp;system in&nbsp;everything. As&nbsp;a&nbsp;rule, they are erudites who don’t like to&nbsp;show&nbsp;off their knowledge. They’re extremely accurate and pedantic not only in&nbsp;the way of&nbsp;thinking, but also in&nbsp;the way of&nbsp;living. They rarely believe in&nbsp;miracles or&nbsp;fate. Having set a&nbsp;goal, they rely on&nbsp;their own diligence and discipline. They’re characterized by&nbsp;consistency, reliability, and always keeping their word.</p><p>LII’s weakness&nbsp;is ethics of&nbsp;relations, which may result in&nbsp;uncertainty and inaccuracy in&nbsp;emotional estimation of&nbsp;others&nbsp;&mdash; clearly seen in&nbsp;an&nbsp;new environment. LII watch the others and try to&nbsp;understand what fits this company, what’s accepted and what’s&nbsp;not. However, they still often fail to&nbsp;fit&nbsp;in. Their cheerfulness or&nbsp;gloominess can&nbsp;be out&nbsp;of&nbsp;place. Due to&nbsp;LII’s weakness in&nbsp;perceiving emotional nuances, they see people in&nbsp;black and white (bad/good, kind/evil, friend/enemy). LII often seem thick-headed and stubborn. They just can’t stand any falsity or&nbsp;lies. They can&nbsp;be solid like a&nbsp;rock in&nbsp;what’s really important for them.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Logical_Intuitive_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t4":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Hamlet&nbsp;&mdash; “Mentor”</h3><p class="representatives">Friedrich Nietzsche<br />Ivan the Terrible<br />Joseph Goebbels<br />Emperor Palpatine (“Star Wars”)<br />Stewie Griffin (“The Family Guy”)</p><p>Ethical-intuitive extraverts (EIE) are people of&nbsp;wasteful emotions, with plenty of&nbsp;actors, producers and musicians among them. “All the world’s a&nbsp;stage, and all the men and women merely players”&nbsp;&mdash; that’s their slogan. They’re capable of&nbsp;presenting the dullest material in&nbsp;an&nbsp;amazingly vivid and interesting manner, being masters of&nbsp;injecting quotes, jokes, puns and anecdotes.</p><p>Often true experts in&nbsp;beauty, they know what’ll become popular, with many adepts of&nbsp;avant-garde art, music and literature among them.</p><p>EIE’s drawback&nbsp;is their “public performance.” Without audience EIE’s enthusiasm fades. They’re known for their extreme fastidiousness, although their home’s usually kept in&nbsp;the state of&nbsp;“artistic mess.” They can put on&nbsp;non-matching garments explaining&nbsp;it by&nbsp;fashion and their own style. Painful inability to&nbsp;think logically sometimes result in&nbsp;a&nbsp;strong desire to&nbsp;appear a&nbsp;business-like person.</p><p>EIE can’t stand physical pain. “The Princess and the Pea”&nbsp;&mdash; that’s about them.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Ethical_Intuitive_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t5":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Maxim Gorky&nbsp;&mdash; “Inspector”</h3><p class="representatives">Joseph Stalin<br />Saddam Hussein<br />Nikita Mikhalkov<br />Batman</p><p>Logical-sensoric introverts (LSI) prefer to&nbsp;act quietly, systematically and rationally. To&nbsp;them, the world is&nbsp;ruled by&nbsp;logic. They respect discipline and order. A&nbsp;model representative of&nbsp;this type was Stalin, who preferred secret methods and craftily eliminated his rivals. LSI’s persistence and patience are often envied by&nbsp;types lacking these features. They back off seeing quietly determined LSI.</p><p>Logical-sensoric introverts&nbsp;&mdash; leaders of&nbsp;a&nbsp;small team&nbsp;&mdash; will usually cope with the task and deliver on&nbsp;time.</p><p>LSI are often blamed for their emotional deafness. Their drawback is&nbsp;weak manifestation of &nbsp;emotions. They are rarely capable of&nbsp;feeling others’ mood. They prefer to&nbsp;base their relationships on&nbsp;admiration. LSI can hardly listen accept or&nbsp;accept criticism. They tend to&nbsp;cling to&nbsp;a&nbsp;formed opinion and consider discussions and debates unnecessary interference with their work, rarely taking advice.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Logical_Sensing_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t6":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Georgy Zhukov&nbsp;&mdash; “Marshal”</h3><p class="representatives">Alexander Lukashenko<br />Vladimir Mayakovsky<br />Voldemort (“Harry Potter”)</p><p>Sensoric-logical extraverts (SLE) aren’t airy-fairy and don’t dream lying on&nbsp;a&nbsp;sofa about things that could’ve happened. They’re practical people, who can&nbsp;be characterized as&nbsp;ambitious, purposeful and strong-willed. Born leaders and administrators, capable of&nbsp;taking responsibility and making important decisions, they appreciate facts and logic.</p><p>SLE’s irrationality shows in&nbsp;that their activity often depends on&nbsp;the&nbsp;mood. They can&nbsp;be very harsh, but if&nbsp;you seek their help in&nbsp;a&nbsp;tough situation, they won’t just talk, but will&nbsp;do everything they can. That is&nbsp;their main virtue.</p><p>SLE’s drawback is&nbsp;their inability to&nbsp;predict the consequences of&nbsp;their harsh words and actions, which often leads to&nbsp;problems coming from nowhere and piling&nbsp;up. SLE see their main goal in&nbsp;being firm. They rarely understand the nuances of&nbsp;people’s relations and push their way through others’ opinions and weaknesses like a&nbsp;tank.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Sensing_Logical_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t7":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Sergei Yesenin&nbsp;&mdash; “Lyricist”</h3><p class="representatives">Yuri Gagarin<br />Cheburashka<br />Susan Mayer/Delfino (“Desperate Housewives”)</p><p>Intuitive-ethical introverts (IEI) are dreamers and romantics, who like to&nbsp;think about future and reminisce about the past. They’re prone to&nbsp;superstition and often believe in&nbsp;omens and prophetic dreams.</p><p>IEI can easily tune into other people’s feelings and understand the deepest aspirations or&nbsp;their soul. Unfortunately, this ability isn’t always used wisely. Instead&nbsp;of&nbsp;comforting people, IEI can start manipulating them. Often whimsical, IEI can sometimes get plain hysterical, because “everything goes wrong” and “nothing turns out to&nbsp;be as&nbsp;expected.”</p><p>In&nbsp;a&nbsp;nutshell, this type is&nbsp;not for hardships. They tend to&nbsp;wallow in&nbsp;the world of&nbsp;illusions, which makes&nbsp;it even harder to&nbsp;muddle through a&nbsp;long-term matter. They can be renovating their house for years, or&nbsp;start moving furniture in&nbsp;the&nbsp;morning and give&nbsp;up by&nbsp;lunch&nbsp;time.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Intuitive_Ethical_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t8":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Napoleon&nbsp;&mdash; “Politician”</h3><p class="representatives">Julius Caesar<br />Elvis Presley<br />Eric Cartman (“Southpark”)<br />Penny (“Big Bang Theory”)</p><p>Sensoric-ethical extraverts (SEE) are born leaders, who’re interested in&nbsp;real-life matters, in&nbsp;which they can enjoy their influence on&nbsp;others. They’re both strong-willed and diplomatic people, who respect and strive for power and the privileges it&nbsp;gives.</p><p>Napoleon Bonaparte, a&nbsp;model SEE, used to&nbsp;say, “Take time to&nbsp;deliberate, but when the time for action has arrived, stop thinking and go&nbsp;in.” SEE are people of&nbsp;uncontrollable passion; if&nbsp;they’re friends&nbsp;&mdash; then to&nbsp;the&nbsp;end; if&nbsp;they love&nbsp;&mdash; they hold nothing back. They live in&nbsp;the&nbsp;moment; future is future, and there’s no&nbsp;reason to&nbsp;regret the past.</p><p>SEE’s drawback&nbsp;is their desire to&nbsp;shine everywhere and for everyone. They’re often blamed for egocentrism, self-conceit, and excessive ambitions.</p><p>SEE are rarely good at&nbsp;planning and scheduling. They often put&nbsp;on a&nbsp;mask of a&nbsp;skillful schemer, but intuition isn’t their strength, and quick victories sometimes turn into defeats. SEE hide their failures&nbsp;&mdash; nothing should shatter the image of&nbsp;a&nbsp;winner. They live in&nbsp;the moment, and sometimes jump on&nbsp;people with their fits of&nbsp;anger.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Sensing_Ethical_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t9":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Honoré de Balzac&nbsp;&mdash; “Critic”</h3><p class="representatives">Winston Churchill<br />Mao Zedong<br />Stephen King<br />Sideshow Bob (“The Simpsons”)</p><p>Intuitive-logical introverts (ILI) can&nbsp;be&nbsp;called the strategists of&nbsp;all strategists. Strong intuition combined with logic give them wisdom and understanding of&nbsp;the laws of&nbsp;life.</p><p>ILI’s morbid inability to&nbsp;show their emotions is&nbsp;probably their biggest drawback. They often seem sullen and sad. However, the mask of&nbsp;perpetual skepticism and pessimism hides an&nbsp;idealist and a&nbsp;dreamer.</p><p>ILI usually pay little attention to&nbsp;their own appearance, preferring simple style in&nbsp;clothes and sometimes coming close to&nbsp;untidiness.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Intuitive_Logical_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t10":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Jack London&nbsp;&mdash; “Enterpriser”</h3><p class="representatives">Barak Obama<br />Bill Gates<br />Brad Pitt<br />Indiana Jones</p><p>Logical-intuitive extraverts (LIE) are born business people. Hard workers, they nonetheless don’t like useless activities&nbsp;&mdash; everything should have a&nbsp;goal.</p><p>LIE are well capable of&nbsp;grasping the gist of&nbsp;a&nbsp;matter, calculating all the details, and solving the problem in&nbsp;the most effective way. At&nbsp;the same time, they’re incorrigible romantics, disposed to&nbsp;travels, adventures and risk. They also appreciate comradeship and friendship.</p><p>LIE’s main problem&nbsp;is their appearance. They often look as&nbsp;if&nbsp;they’ve just returned from a&nbsp;trip: men unshaved, women’s hair gone mad. There are so&nbsp;many important things to&nbsp;do that they have absolutely no&nbsp;time for&nbsp;themselves. They don’t like improvising. In&nbsp;the&nbsp;kitchen, they’d rather take a&nbsp;cook-book and follow a&nbsp;recipe to&nbsp;the&nbsp;word than experiment.</p><p>LIE’s spontaneity in&nbsp;demonstration of&nbsp;emotions can&nbsp;be compared to&nbsp;a&nbsp;sudden downpour&nbsp;&mdash; it&nbsp;can&nbsp;be too much for the people around.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Logical_Intuitive_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t11":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Theodore Dreiser&nbsp;&mdash; “Guardian”</h3><p class="representatives">Leonid Brezhnev<br />Tom Hanks<br />Marge Simpson (“The Simpsons”)<br />Sheila Broflovski (“Southpark”)</p><p>Ethical-sensoric introverts (ESI) are real stoics and guardians of&nbsp;moral principles of&nbsp;society. There are many lawyers, investigators, doctors and teachers among them. ESI women are known for upholding family values, and bearing the burden of&nbsp;a&nbsp;career, house chores and raising children without a&nbsp;complaint.</p><p>No&nbsp;other type can&nbsp;be compared to&nbsp;ESI in&nbsp;terms of&nbsp;selflessness and reliability. Fighting evil&nbsp;is their prominent feature.</p><p>ESI’s drawback&nbsp;is their excessive rationality and orthodoxy. They’d always choose duty over love, which often leads to&nbsp;them missing&nbsp;on promising relationships, and turning into hostages of&nbsp;inner loneliness.</p><p>ESI, being at&nbsp;odds with intuition for opportunities, are well capable of&nbsp;untimely initiatives.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Ethical_Sensing_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t12":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Sherlock Holmes&nbsp;&mdash; “Administrator”</h3><p class="representatives">Harrison Ford<br />George Clooney<br />Sylvester Stallone<br />Sherlock Holmes</p><p>Logical-sensoric extraverts (LSE) are good at&nbsp;telling apart important and secondary. As&nbsp;any logical type, they hate rush, fuss and nervousness. They’re business-like, focused, consistent. They’re also reasonable in&nbsp;estimation of&nbsp;their own abilities.</p><p>LSE have good taste and are also good at&nbsp;handwork, which usuually results in&nbsp;a&nbsp;combination of&nbsp;beauty and functionality.</p><p>LSE’s drawback&nbsp;is their tendency to&nbsp;stability and predictability, which may show in&nbsp;conservatism and lack of&nbsp;foresight. Despite their extraversion, LSE aren’t inclined to&nbsp;start new relationships, following the principle “Old friends and old wine are best.” If&nbsp;they’re unsatisfied with their family life, they’d still rarely choose solitude.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Logical_Sensing_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t13":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Fyodor Dostoyevsky&nbsp;&mdash; “Humanist”</h3><p class="representatives">Mahatma Gandhi<br />Vincent van Gogh<br />Michael Jackson<br />Doctor Watson<br />Harry Potter</p><p>Ethical-intuitive introverts (EII) put ethics and morals above everythinng. They always seek new, better forms of&nbsp;human relationships, seeing every person as&nbsp;a&nbsp;small universe, where good and beauty fight evil and ugliness. Whatever their age, EII are pastors, spiritual and moral mentors. They’re always where there’s grief, where someone needs a&nbsp;shoulder to&nbsp;cry&nbsp;on.</p><p>EII’s favourite words are derivatives of&nbsp;“must.” Sometimes they can make a&nbsp;big fuss over nothing. Spending their days in&nbsp;philosophic reflection, which rarely has any practical use, EII are often unable to&nbsp;arrange their own everyday life.</p><p>Well capable of&nbsp;sacrificing themselves (which doesn’t mean it’s always necessary), EII don’t resist pressure too well. Steamroller approach can&nbsp;be very destructive against them.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Ethical_Intuitive_Introtim" target="_blank">Further reading</a></p>';
			break;
		case "t14":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Aldous Huxley&nbsp;&mdash; “Psychologist”</h3><p class="representatives">Mark Twain<br />Tom Sawyer<br />Monica Geller (“Friends”)<br />Donkey (“Shrek”)</p><p>Intuitive-ethical extraverts (IEE) are born psychologists and advisors. Buoyant and easy-going, they easily grasp the gist of&nbsp;people’s problems and desires. Their unconventional thinking often lets them discover unexpected merits and talents in&nbsp;other people. Naturally warm and charming, they’re good at&nbsp;keeping good relations with former spouses, partners and colleagues.</p><p>IEE’s drawback&nbsp;is their inability to&nbsp;perform systematic and routine tasks. They can blatantly miss deadlines on&nbsp;thesis papers, quarterly reports and everything else important.</p><p>With all their pacifism and friendliness, sometimes IEE can show strong will and determination to&nbsp;hit the target, but later regret their harsh words and actions, and seek reconciliation.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Intuitive_Ethical_Extratim" target="_blank">Further reading</a></p>';
			break;
		case "t15":
			document.getElementById('sociotypeDescription').innerHTML = '<h3>Jean Gabin&nbsp;&mdash; “Craftsman”</h3><p class="representatives">Steven Seagal<br />Chuck Norris<br />Huckleberry Finn<br />Shrek</p><p>Sensoric-logical introverts (SLI) prefer a&nbsp;bird in&nbsp;hand to&nbsp;two in&nbsp;the&nbsp;bush. With a&nbsp;talent in&nbsp;everything related to&nbsp;handwork, they’re just so&nbsp;good in&nbsp;creating comfort in&nbsp;their everyday life. They like expensive clothes showing their high status.</p><p>SLI’s weaknesses are ethics of&nbsp;emotions and intuition of&nbsp;time.</p><p>Very vulnerable and secretly afraid of&nbsp;being misunderstood, they prefer to&nbsp;hide their true attitude to&nbsp;others. However, if&nbsp;humiliated in&nbsp;public, they can lose their temper and burst into tears and/or shout at&nbsp;the&nbsp;offender. SLI remember even the smallest offence and can break a&nbsp;relationship after a&nbsp;serious quarrel.</p><p>SLI’s weak intuition of&nbsp;time shows in&nbsp;their desire to&nbsp;plan everything in&nbsp;advance. Excessively conservative and cautious, they’ll never make a&nbsp;final decision without a&nbsp;thorough and detailed analysis.</p><p><a href="http://www.wikisocion.org/en/index.php?title=Sensing_Logical_Introtim" target="_blank">Further reading</a></p>';
			break;
	}
}